import { ScoreData } from '../types/music';

/**
 * Rich preset pieces for immediate testing, rehearsal, and arrangement editing
 */

export const PRESET_ODE_AN_DIE_FREUDE: ScoreData = {
  title: 'Ode an die Freude (Sinfonie Nr. 9)',
  artist: 'Ludwig van Beethoven / Friedrich Schiller',
  bpm: 116,
  timeSignature: { beats: 4, beatUnit: 4 },
  key: 'D-Dur',
  choralGuidance: {
    generalAdvice:
      'Festlicher, getragener Chorklang (Tutti mit strahlendem Forte). Vokale "eu" und "ö" schlank und obertonreich führen.',
    breathingTechnique:
      'Atemzeichen nach jeweils 2 Takten beachten. Nicht mitten im Wort "Götter-funken" atmen.',
    vocalTuningTips:
      'Sopran: Fis5 im Takt 3 schlank ansetzen, nicht drücken. Bass: klares Fundament auf D3/A2.',
    suggestedWarmups: ['M-m-m auf D-Dur Akkord', 'Staccato Übungen auf "Ha-ha-ha"'],
  },
  sections: [
    { name: 'Choreinstieg (Thema)', startMeasure: 1, endMeasure: 4 },
    { name: 'Fortführung & Steigerung', startMeasure: 5, endMeasure: 8 },
  ],
  tracks: [
    {
      id: 'track-sopran',
      name: 'Sopran (Chor)',
      instrument: 'choir_soprano',
      clef: 'treble',
      choralRole: 'Hauptmelodie (Cantus Firmus)',
      vocalRange: 'D4 – G5',
      volume: 0.9,
      isMuted: false,
      isSolo: false,
      notes: [
        // Takt 1: Freu-de, schö-ner
        { id: 'sop-1', pitch: 'F#4', midiNote: 66, startBeat: 0, durationBeats: 1, lyric: 'Freu-', choralMarking: 'mf cantabile' },
        { id: 'sop-2', pitch: 'F#4', midiNote: 66, startBeat: 1, durationBeats: 1, lyric: '-de,' },
        { id: 'sop-3', pitch: 'G4', midiNote: 67, startBeat: 2, durationBeats: 1, lyric: 'schö-' },
        { id: 'sop-4', pitch: 'A4', midiNote: 69, startBeat: 3, durationBeats: 1, lyric: '-ner' },
        // Takt 2: Göt-ter-fun-ken,
        { id: 'sop-5', pitch: 'A4', midiNote: 69, startBeat: 4, durationBeats: 1, lyric: 'Göt-' },
        { id: 'sop-6', pitch: 'G4', midiNote: 67, startBeat: 5, durationBeats: 1, lyric: '-ter-' },
        { id: 'sop-7', pitch: 'F#4', midiNote: 66, startBeat: 6, durationBeats: 1, lyric: 'fun-' },
        { id: 'sop-8', pitch: 'E4', midiNote: 64, startBeat: 7, durationBeats: 1, lyric: '-ken,', choralMarking: 'Atem' },
        // Takt 3: Toch-ter aus E-
        { id: 'sop-9', pitch: 'D4', midiNote: 62, startBeat: 8, durationBeats: 1, lyric: 'Toch-' },
        { id: 'sop-10', pitch: 'D4', midiNote: 62, startBeat: 9, durationBeats: 1, lyric: '-ter' },
        { id: 'sop-11', pitch: 'E4', midiNote: 64, startBeat: 10, durationBeats: 1, lyric: 'aus' },
        { id: 'sop-12', pitch: 'F#4', midiNote: 66, startBeat: 11, durationBeats: 1, lyric: 'E-' },
        // Takt 4: -ly-si-um
        { id: 'sop-13', pitch: 'F#4', midiNote: 66, startBeat: 12, durationBeats: 1.5, lyric: '-ly-' },
        { id: 'sop-14', pitch: 'E4', midiNote: 64, startBeat: 13.5, durationBeats: 0.5, lyric: '-si-' },
        { id: 'sop-15', pitch: 'E4', midiNote: 64, startBeat: 14, durationBeats: 2, lyric: '-um,', choralMarking: 'Atem' },
        // Takt 5: Wir be-tre-ten
        { id: 'sop-16', pitch: 'F#4', midiNote: 66, startBeat: 16, durationBeats: 1, lyric: 'Wir' },
        { id: 'sop-17', pitch: 'F#4', midiNote: 66, startBeat: 17, durationBeats: 1, lyric: 'be-' },
        { id: 'sop-18', pitch: 'G4', midiNote: 67, startBeat: 18, durationBeats: 1, lyric: '-tre-' },
        { id: 'sop-19', pitch: 'A4', midiNote: 69, startBeat: 19, durationBeats: 1, lyric: '-ten' },
        // Takt 6: feu-er-trun-ken
        { id: 'sop-20', pitch: 'A4', midiNote: 69, startBeat: 20, durationBeats: 1, lyric: 'feu-' },
        { id: 'sop-21', pitch: 'G4', midiNote: 67, startBeat: 21, durationBeats: 1, lyric: '-er-' },
        { id: 'sop-22', pitch: 'F#4', midiNote: 66, startBeat: 22, durationBeats: 1, lyric: 'trun-' },
        { id: 'sop-23', pitch: 'E4', midiNote: 64, startBeat: 23, durationBeats: 1, lyric: '-ken,', choralMarking: 'Atem' },
        // Takt 7: Himm-li-sche, dein
        { id: 'sop-24', pitch: 'D4', midiNote: 62, startBeat: 24, durationBeats: 1, lyric: 'Himm-' },
        { id: 'sop-25', pitch: 'D4', midiNote: 62, startBeat: 25, durationBeats: 1, lyric: '-li-' },
        { id: 'sop-26', pitch: 'E4', midiNote: 64, startBeat: 26, durationBeats: 1, lyric: '-sche,' },
        { id: 'sop-27', pitch: 'F#4', midiNote: 66, startBeat: 27, durationBeats: 1, lyric: 'dein' },
        // Takt 8: Hei-lig-tum!
        { id: 'sop-28', pitch: 'E4', midiNote: 64, startBeat: 28, durationBeats: 1.5, lyric: 'Hei-' },
        { id: 'sop-29', pitch: 'D4', midiNote: 62, startBeat: 29.5, durationBeats: 0.5, lyric: '-lig-' },
        { id: 'sop-30', pitch: 'D4', midiNote: 62, startBeat: 30, durationBeats: 2, lyric: '-tum!', choralMarking: 'f Tutti' },
      ],
    },
    {
      id: 'track-alt',
      name: 'Alt (Chor)',
      instrument: 'choir_alto',
      clef: 'treble',
      choralRole: 'Mittelstimme / Terzharmonie',
      vocalRange: 'A3 – D5',
      volume: 0.85,
      isMuted: false,
      isSolo: false,
      notes: [
        { id: 'alt-1', pitch: 'D4', midiNote: 62, startBeat: 0, durationBeats: 1, lyric: 'Freu-' },
        { id: 'alt-2', pitch: 'D4', midiNote: 62, startBeat: 1, durationBeats: 1, lyric: '-de,' },
        { id: 'alt-3', pitch: 'E4', midiNote: 64, startBeat: 2, durationBeats: 1, lyric: 'schö-' },
        { id: 'alt-4', pitch: 'F#4', midiNote: 66, startBeat: 3, durationBeats: 1, lyric: '-ner' },
        { id: 'alt-5', pitch: 'F#4', midiNote: 66, startBeat: 4, durationBeats: 1, lyric: 'Göt-' },
        { id: 'alt-6', pitch: 'E4', midiNote: 64, startBeat: 5, durationBeats: 1, lyric: '-ter-' },
        { id: 'alt-7', pitch: 'D4', midiNote: 62, startBeat: 6, durationBeats: 1, lyric: 'fun-' },
        { id: 'alt-8', pitch: 'C#4', midiNote: 61, startBeat: 7, durationBeats: 1, lyric: '-ken,' },
        { id: 'alt-9', pitch: 'D4', midiNote: 62, startBeat: 8, durationBeats: 1, lyric: 'Toch-' },
        { id: 'alt-10', pitch: 'B3', midiNote: 59, startBeat: 9, durationBeats: 1, lyric: '-ter' },
        { id: 'alt-11', pitch: 'C#4', midiNote: 61, startBeat: 10, durationBeats: 1, lyric: 'aus' },
        { id: 'alt-12', pitch: 'D4', midiNote: 62, startBeat: 11, durationBeats: 1, lyric: 'E-' },
        { id: 'alt-13', pitch: 'D4', midiNote: 62, startBeat: 12, durationBeats: 1.5, lyric: '-ly-' },
        { id: 'alt-14', pitch: 'C#4', midiNote: 61, startBeat: 13.5, durationBeats: 0.5, lyric: '-si-' },
        { id: 'alt-15', pitch: 'C#4', midiNote: 61, startBeat: 14, durationBeats: 2, lyric: '-um,' },
        // Takte 5-8
        { id: 'alt-16', pitch: 'D4', midiNote: 62, startBeat: 16, durationBeats: 1, lyric: 'Wir' },
        { id: 'alt-17', pitch: 'D4', midiNote: 62, startBeat: 17, durationBeats: 1, lyric: 'be-' },
        { id: 'alt-18', pitch: 'E4', midiNote: 64, startBeat: 18, durationBeats: 1, lyric: '-tre-' },
        { id: 'alt-19', pitch: 'F#4', midiNote: 66, startBeat: 19, durationBeats: 1, lyric: '-ten' },
        { id: 'alt-20', pitch: 'F#4', midiNote: 66, startBeat: 20, durationBeats: 1, lyric: 'feu-' },
        { id: 'alt-21', pitch: 'E4', midiNote: 64, startBeat: 21, durationBeats: 1, lyric: '-er-' },
        { id: 'alt-22', pitch: 'D4', midiNote: 62, startBeat: 22, durationBeats: 1, lyric: 'trun-' },
        { id: 'alt-23', pitch: 'C#4', midiNote: 61, startBeat: 23, durationBeats: 1, lyric: '-ken,' },
        { id: 'alt-24', pitch: 'D4', midiNote: 62, startBeat: 24, durationBeats: 1, lyric: 'Himm-' },
        { id: 'alt-25', pitch: 'B3', midiNote: 59, startBeat: 25, durationBeats: 1, lyric: '-li-' },
        { id: 'alt-26', pitch: 'C#4', midiNote: 61, startBeat: 26, durationBeats: 1, lyric: '-sche,' },
        { id: 'alt-27', pitch: 'D4', midiNote: 62, startBeat: 27, durationBeats: 1, lyric: 'dein' },
        { id: 'alt-28', pitch: 'C#4', midiNote: 61, startBeat: 28, durationBeats: 1.5, lyric: 'Hei-' },
        { id: 'alt-29', pitch: 'A3', midiNote: 57, startBeat: 29.5, durationBeats: 0.5, lyric: '-lig-' },
        { id: 'alt-30', pitch: 'F#3', midiNote: 54, startBeat: 30, durationBeats: 2, lyric: '-tum!' },
      ],
    },
    {
      id: 'track-tenor',
      name: 'Tenor (Chor)',
      instrument: 'choir_tenor',
      clef: 'treble',
      choralRole: 'Männerstimme / Gegenmelodie',
      vocalRange: 'D3 – G4',
      volume: 0.85,
      isMuted: false,
      isSolo: false,
      notes: [
        { id: 'ten-1', pitch: 'A3', midiNote: 57, startBeat: 0, durationBeats: 1, lyric: 'Freu-' },
        { id: 'ten-2', pitch: 'A3', midiNote: 57, startBeat: 1, durationBeats: 1, lyric: '-de,' },
        { id: 'ten-3', pitch: 'B3', midiNote: 59, startBeat: 2, durationBeats: 1, lyric: 'schö-' },
        { id: 'ten-4', pitch: 'C#4', midiNote: 61, startBeat: 3, durationBeats: 1, lyric: '-ner' },
        { id: 'ten-5', pitch: 'D4', midiNote: 62, startBeat: 4, durationBeats: 1, lyric: 'Göt-' },
        { id: 'ten-6', pitch: 'B3', midiNote: 59, startBeat: 5, durationBeats: 1, lyric: '-ter-' },
        { id: 'ten-7', pitch: 'A3', midiNote: 57, startBeat: 6, durationBeats: 1, lyric: 'fun-' },
        { id: 'ten-8', pitch: 'A3', midiNote: 57, startBeat: 7, durationBeats: 1, lyric: '-ken,' },
        { id: 'ten-9', pitch: 'F#3', midiNote: 54, startBeat: 8, durationBeats: 1, lyric: 'Toch-' },
        { id: 'ten-10', pitch: 'G3', midiNote: 55, startBeat: 9, durationBeats: 1, lyric: '-ter' },
        { id: 'ten-11', pitch: 'A3', midiNote: 57, startBeat: 10, durationBeats: 1, lyric: 'aus' },
        { id: 'ten-12', pitch: 'A3', midiNote: 57, startBeat: 11, durationBeats: 1, lyric: 'E-' },
        { id: 'ten-13', pitch: 'A3', midiNote: 57, startBeat: 12, durationBeats: 1.5, lyric: '-ly-' },
        { id: 'ten-14', pitch: 'G3', midiNote: 55, startBeat: 13.5, durationBeats: 0.5, lyric: '-si-' },
        { id: 'ten-15', pitch: 'A3', midiNote: 57, startBeat: 14, durationBeats: 2, lyric: '-um,' },
        // Takte 5-8
        { id: 'ten-16', pitch: 'A3', midiNote: 57, startBeat: 16, durationBeats: 1, lyric: 'Wir' },
        { id: 'ten-17', pitch: 'A3', midiNote: 57, startBeat: 17, durationBeats: 1, lyric: 'be-' },
        { id: 'ten-18', pitch: 'B3', midiNote: 59, startBeat: 18, durationBeats: 1, lyric: '-tre-' },
        { id: 'ten-19', pitch: 'C#4', midiNote: 61, startBeat: 19, durationBeats: 1, lyric: '-ten' },
        { id: 'ten-20', pitch: 'D4', midiNote: 62, startBeat: 20, durationBeats: 1, lyric: 'feu-' },
        { id: 'ten-21', pitch: 'B3', midiNote: 59, startBeat: 21, durationBeats: 1, lyric: '-er-' },
        { id: 'ten-22', pitch: 'A3', midiNote: 57, startBeat: 22, durationBeats: 1, lyric: 'trun-' },
        { id: 'ten-23', pitch: 'A3', midiNote: 57, startBeat: 23, durationBeats: 1, lyric: '-ken,' },
        { id: 'ten-24', pitch: 'F#3', midiNote: 54, startBeat: 24, durationBeats: 1, lyric: 'Himm-' },
        { id: 'ten-25', pitch: 'G3', midiNote: 55, startBeat: 25, durationBeats: 1, lyric: '-li-' },
        { id: 'ten-26', pitch: 'A3', midiNote: 57, startBeat: 26, durationBeats: 1, lyric: '-sche,' },
        { id: 'ten-27', pitch: 'A3', midiNote: 57, startBeat: 27, durationBeats: 1, lyric: 'dein' },
        { id: 'ten-28', pitch: 'A3', midiNote: 57, startBeat: 28, durationBeats: 1.5, lyric: 'Hei-' },
        { id: 'ten-29', pitch: 'G3', midiNote: 55, startBeat: 29.5, durationBeats: 0.5, lyric: '-lig-' },
        { id: 'ten-30', pitch: 'F#3', midiNote: 54, startBeat: 30, durationBeats: 2, lyric: '-tum!' },
      ],
    },
    {
      id: 'track-bass',
      name: 'Bass (Chor)',
      instrument: 'choir_bass',
      clef: 'bass',
      choralRole: 'Harmonisches Fundament',
      vocalRange: 'D2 – D4',
      volume: 0.9,
      isMuted: false,
      isSolo: false,
      notes: [
        { id: 'bas-1', pitch: 'D3', midiNote: 50, startBeat: 0, durationBeats: 1, lyric: 'Freu-' },
        { id: 'bas-2', pitch: 'D3', midiNote: 50, startBeat: 1, durationBeats: 1, lyric: '-de,' },
        { id: 'bas-3', pitch: 'G2', midiNote: 43, startBeat: 2, durationBeats: 1, lyric: 'schö-' },
        { id: 'bas-4', pitch: 'F#2', midiNote: 42, startBeat: 3, durationBeats: 1, lyric: '-ner' },
        { id: 'bas-5', pitch: 'D3', midiNote: 50, startBeat: 4, durationBeats: 1, lyric: 'Göt-' },
        { id: 'bas-6', pitch: 'G2', midiNote: 43, startBeat: 5, durationBeats: 1, lyric: '-ter-' },
        { id: 'bas-7', pitch: 'D3', midiNote: 50, startBeat: 6, durationBeats: 1, lyric: 'fun-' },
        { id: 'bas-8', pitch: 'A2', midiNote: 45, startBeat: 7, durationBeats: 1, lyric: '-ken,' },
        { id: 'bas-9', pitch: 'D3', midiNote: 50, startBeat: 8, durationBeats: 1, lyric: 'Toch-' },
        { id: 'bas-10', pitch: 'G2', midiNote: 43, startBeat: 9, durationBeats: 1, lyric: '-ter' },
        { id: 'bas-11', pitch: 'A2', midiNote: 45, startBeat: 10, durationBeats: 1, lyric: 'aus' },
        { id: 'bas-12', pitch: 'D3', midiNote: 50, startBeat: 11, durationBeats: 1, lyric: 'E-' },
        { id: 'bas-13', pitch: 'D3', midiNote: 50, startBeat: 12, durationBeats: 1.5, lyric: '-ly-' },
        { id: 'bas-14', pitch: 'A2', midiNote: 45, startBeat: 13.5, durationBeats: 0.5, lyric: '-si-' },
        { id: 'bas-15', pitch: 'A2', midiNote: 45, startBeat: 14, durationBeats: 2, lyric: '-um,' },
        // Takte 5-8
        { id: 'bas-16', pitch: 'D3', midiNote: 50, startBeat: 16, durationBeats: 1, lyric: 'Wir' },
        { id: 'bas-17', pitch: 'D3', midiNote: 50, startBeat: 17, durationBeats: 1, lyric: 'be-' },
        { id: 'bas-18', pitch: 'G2', midiNote: 43, startBeat: 18, durationBeats: 1, lyric: '-tre-' },
        { id: 'bas-19', pitch: 'F#2', midiNote: 42, startBeat: 19, durationBeats: 1, lyric: '-ten' },
        { id: 'bas-20', pitch: 'D3', midiNote: 50, startBeat: 20, durationBeats: 1, lyric: 'feu-' },
        { id: 'bas-21', pitch: 'G2', midiNote: 43, startBeat: 21, durationBeats: 1, lyric: '-er-' },
        { id: 'bas-22', pitch: 'D3', midiNote: 50, startBeat: 22, durationBeats: 1, lyric: 'trun-' },
        { id: 'bas-23', pitch: 'A2', midiNote: 45, startBeat: 23, durationBeats: 1, lyric: '-ken,' },
        { id: 'bas-24', pitch: 'D3', midiNote: 50, startBeat: 24, durationBeats: 1, lyric: 'Himm-' },
        { id: 'bas-25', pitch: 'G2', midiNote: 43, startBeat: 25, durationBeats: 1, lyric: '-li-' },
        { id: 'bas-26', pitch: 'A2', midiNote: 45, startBeat: 26, durationBeats: 1, lyric: '-sche,' },
        { id: 'bas-27', pitch: 'D3', midiNote: 50, startBeat: 27, durationBeats: 1, lyric: 'dein' },
        { id: 'bas-28', pitch: 'A2', midiNote: 45, startBeat: 28, durationBeats: 1.5, lyric: 'Hei-' },
        { id: 'bas-29', pitch: 'A2', midiNote: 45, startBeat: 29.5, durationBeats: 0.5, lyric: '-lig-' },
        { id: 'bas-30', pitch: 'D3', midiNote: 50, startBeat: 30, durationBeats: 2, lyric: '-tum!' },
      ],
    },
    {
      id: 'track-piano',
      name: 'Klavier (Begleitung)',
      instrument: 'piano',
      clef: 'treble',
      choralRole: 'Instrumentale Stütze',
      volume: 0.75,
      isMuted: false,
      isSolo: false,
      notes: [
        { id: 'pno-1', pitch: 'D4', midiNote: 62, startBeat: 0, durationBeats: 2 },
        { id: 'pno-2', pitch: 'F#4', midiNote: 66, startBeat: 2, durationBeats: 2 },
        { id: 'pno-3', pitch: 'A4', midiNote: 69, startBeat: 4, durationBeats: 2 },
        { id: 'pno-4', pitch: 'G4', midiNote: 67, startBeat: 6, durationBeats: 2 },
        { id: 'pno-5', pitch: 'F#4', midiNote: 66, startBeat: 8, durationBeats: 2 },
        { id: 'pno-6', pitch: 'E4', midiNote: 64, startBeat: 10, durationBeats: 2 },
        { id: 'pno-7', pitch: 'D4', midiNote: 62, startBeat: 12, durationBeats: 4 },
        { id: 'pno-8', pitch: 'F#4', midiNote: 66, startBeat: 16, durationBeats: 2 },
        { id: 'pno-9', pitch: 'A4', midiNote: 69, startBeat: 18, durationBeats: 2 },
        { id: 'pno-10', pitch: 'D5', midiNote: 74, startBeat: 20, durationBeats: 2 },
        { id: 'pno-11', pitch: 'A4', midiNote: 69, startBeat: 22, durationBeats: 2 },
        { id: 'pno-12', pitch: 'F#4', midiNote: 66, startBeat: 24, durationBeats: 2 },
        { id: 'pno-13', pitch: 'E4', midiNote: 64, startBeat: 26, durationBeats: 2 },
        { id: 'pno-14', pitch: 'D4', midiNote: 62, startBeat: 28, durationBeats: 4 },
      ],
    },
  ],
};

export const PRESET_DER_MOND: ScoreData = {
  title: 'Der Mond ist aufgegangen',
  artist: 'Matthias Claudius / J. A. P. Schulz',
  bpm: 84,
  timeSignature: { beats: 4, beatUnit: 4 },
  key: 'F-Dur',
  choralGuidance: {
    generalAdvice:
      'Sehr zartes, intimes Pianissimo (pp). Ruhiger Abendchoral mit weiter Atemführung.',
    breathingTechnique: 'Zwischen den Verszeilen geräuschlos einatmen.',
    vocalTuningTips: 'Reine Terzen im F-Dur Akkord (A4 und F4) besonders rein intonieren.',
  },
  sections: [
    { name: 'Strophe 1 (Chorsatz)', startMeasure: 1, endMeasure: 4 },
  ],
  tracks: [
    {
      id: 'mond-sopran',
      name: 'Sopran / Lead Gesang',
      instrument: 'choir_soprano',
      clef: 'treble',
      choralRole: 'Melodie',
      vocalRange: 'F4 – F5',
      volume: 0.9,
      isMuted: false,
      isSolo: false,
      notes: [
        { id: 'm-s1', pitch: 'F4', midiNote: 65, startBeat: 0, durationBeats: 1, lyric: 'Der' },
        { id: 'm-s2', pitch: 'G4', midiNote: 67, startBeat: 1, durationBeats: 1, lyric: 'Mond' },
        { id: 'm-s3', pitch: 'A4', midiNote: 69, startBeat: 2, durationBeats: 1, lyric: 'ist' },
        { id: 'm-s4', pitch: 'B4', midiNote: 71, startBeat: 3, durationBeats: 1, lyric: 'auf-' },
        { id: 'm-s5', pitch: 'C5', midiNote: 72, startBeat: 4, durationBeats: 2, lyric: '-ge-' },
        { id: 'm-s6', pitch: 'A4', midiNote: 69, startBeat: 6, durationBeats: 2, lyric: '-gan-gen,', choralMarking: 'p Atem' },
        { id: 'm-s7', pitch: 'C5', midiNote: 72, startBeat: 8, durationBeats: 1, lyric: 'die' },
        { id: 'm-s8', pitch: 'C5', midiNote: 72, startBeat: 9, durationBeats: 1, lyric: 'gold-' },
        { id: 'm-s9', pitch: 'B4', midiNote: 71, startBeat: 10, durationBeats: 1, lyric: '-nen' },
        { id: 'm-s10', pitch: 'A4', midiNote: 69, startBeat: 11, durationBeats: 1, lyric: 'Stern-' },
        { id: 'm-s11', pitch: 'G4', midiNote: 67, startBeat: 12, durationBeats: 4, lyric: '-lein prangen' },
      ],
    },
    {
      id: 'mond-alt',
      name: 'Alt (Harmonie)',
      instrument: 'choir_alto',
      clef: 'treble',
      choralRole: 'Terzbegleitung',
      vocalRange: 'C4 – A4',
      volume: 0.8,
      isMuted: false,
      isSolo: false,
      notes: [
        { id: 'm-a1', pitch: 'C4', midiNote: 60, startBeat: 0, durationBeats: 1, lyric: 'Der' },
        { id: 'm-a2', pitch: 'E4', midiNote: 64, startBeat: 1, durationBeats: 1, lyric: 'Mond' },
        { id: 'm-a3', pitch: 'F4', midiNote: 65, startBeat: 2, durationBeats: 1, lyric: 'ist' },
        { id: 'm-a4', pitch: 'G4', midiNote: 67, startBeat: 3, durationBeats: 1, lyric: 'auf-' },
        { id: 'm-a5', pitch: 'A4', midiNote: 69, startBeat: 4, durationBeats: 2, lyric: '-ge-' },
        { id: 'm-a6', pitch: 'F4', midiNote: 65, startBeat: 6, durationBeats: 2, lyric: '-gan-gen,' },
        { id: 'm-a7', pitch: 'A4', midiNote: 69, startBeat: 8, durationBeats: 1, lyric: 'die' },
        { id: 'm-a8', pitch: 'A4', midiNote: 69, startBeat: 9, durationBeats: 1, lyric: 'gold-' },
        { id: 'm-a9', pitch: 'G4', midiNote: 67, startBeat: 10, durationBeats: 1, lyric: '-nen' },
        { id: 'm-a10', pitch: 'F4', midiNote: 65, startBeat: 11, durationBeats: 1, lyric: 'Stern-' },
        { id: 'm-a11', pitch: 'E4', midiNote: 64, startBeat: 12, durationBeats: 4, lyric: '-lein' },
      ],
    },
    {
      id: 'mond-bass',
      name: 'Bass (Chor)',
      instrument: 'choir_bass',
      clef: 'bass',
      choralRole: 'Bassfundament',
      vocalRange: 'F2 – C4',
      volume: 0.85,
      isMuted: false,
      isSolo: false,
      notes: [
        { id: 'm-b1', pitch: 'F2', midiNote: 41, startBeat: 0, durationBeats: 1, lyric: 'Der' },
        { id: 'm-b2', pitch: 'C3', midiNote: 48, startBeat: 1, durationBeats: 1, lyric: 'Mond' },
        { id: 'm-b3', pitch: 'F3', midiNote: 53, startBeat: 2, durationBeats: 1, lyric: 'ist' },
        { id: 'm-b4', pitch: 'E3', midiNote: 52, startBeat: 3, durationBeats: 1, lyric: 'auf-' },
        { id: 'm-b5', pitch: 'F3', midiNote: 53, startBeat: 4, durationBeats: 2, lyric: '-ge-' },
        { id: 'm-b6', pitch: 'D3', midiNote: 50, startBeat: 6, durationBeats: 2, lyric: '-gan-gen,' },
        { id: 'm-b7', pitch: 'F3', midiNote: 53, startBeat: 8, durationBeats: 1, lyric: 'die' },
        { id: 'm-b8', pitch: 'F3', midiNote: 53, startBeat: 9, durationBeats: 1, lyric: 'gold-' },
        { id: 'm-b9', pitch: 'C3', midiNote: 48, startBeat: 10, durationBeats: 1, lyric: '-nen' },
        { id: 'm-b10', pitch: 'D3', midiNote: 50, startBeat: 11, durationBeats: 1, lyric: 'Stern-' },
        { id: 'm-b11', pitch: 'C3', midiNote: 48, startBeat: 12, durationBeats: 4, lyric: '-lein' },
      ],
    },
    {
      id: 'mond-strings',
      name: 'Streicher-Ensemble',
      instrument: 'strings',
      clef: 'treble',
      volume: 0.7,
      isMuted: false,
      isSolo: false,
      notes: [
        { id: 'm-str1', pitch: 'F4', midiNote: 65, startBeat: 0, durationBeats: 4 },
        { id: 'm-str2', pitch: 'A4', midiNote: 69, startBeat: 4, durationBeats: 4 },
        { id: 'm-str3', pitch: 'F4', midiNote: 65, startBeat: 8, durationBeats: 4 },
        { id: 'm-str4', pitch: 'E4', midiNote: 64, startBeat: 12, durationBeats: 4 },
      ],
    },
  ],
};

export const PRESET_ACOUSTIC_BALLAD: ScoreData = {
  title: 'Hymn of Light (Vocal & Guitar)',
  artist: 'Akustik-Ballade mit Chor-Refrain',
  bpm: 96,
  timeSignature: { beats: 4, beatUnit: 4 },
  key: 'G-Dur',
  choralGuidance: {
    generalAdvice:
      'Gefühlvoller Einstieg mit Solo-Gesang in den ersten 4 Takten, danach tritt der mehrstimmige Chor mit warmen Vokalisen ("Ooh-Aah") ein.',
    breathingTechnique: 'Weicher Stimmbandschluss, Falsett / Kopfstimme im oberen Bereich erlaubt.',
  },
  sections: [
    { name: 'Strophe (Solo Gesang & Gitarre)', startMeasure: 1, endMeasure: 2 },
    { name: 'Choreinstieg (Harmonie & Bass)', startMeasure: 3, endMeasure: 4 },
  ],
  tracks: [
    {
      id: 'ballad-lead',
      name: 'Lead Gesang',
      instrument: 'lead_vocal',
      clef: 'treble',
      choralRole: 'Solo Melodieführung',
      vocalRange: 'G3 – E5',
      volume: 0.95,
      isMuted: false,
      isSolo: false,
      notes: [
        { id: 'b-v1', pitch: 'G4', midiNote: 67, startBeat: 0, durationBeats: 1, lyric: 'See' },
        { id: 'b-v2', pitch: 'B4', midiNote: 71, startBeat: 1, durationBeats: 1, lyric: 'the' },
        { id: 'b-v3', pitch: 'D5', midiNote: 74, startBeat: 2, durationBeats: 1.5, lyric: 'morn-' },
        { id: 'b-v4', pitch: 'C5', midiNote: 72, startBeat: 3.5, durationBeats: 0.5, lyric: '-ing' },
        { id: 'b-v5', pitch: 'B4', midiNote: 71, startBeat: 4, durationBeats: 2, lyric: 'light' },
        { id: 'b-v6', pitch: 'A4', midiNote: 69, startBeat: 6, durationBeats: 2, lyric: 'shine,', choralMarking: 'Atem' },
        { id: 'b-v7', pitch: 'G4', midiNote: 67, startBeat: 8, durationBeats: 1, lyric: 'all' },
        { id: 'b-v8', pitch: 'B4', midiNote: 71, startBeat: 9, durationBeats: 1, lyric: 'the' },
        { id: 'b-v9', pitch: 'D5', midiNote: 74, startBeat: 10, durationBeats: 2, lyric: 'voi-' },
        { id: 'b-v10', pitch: 'E5', midiNote: 76, startBeat: 12, durationBeats: 2, lyric: '-ces' },
        { id: 'b-v11', pitch: 'D5', midiNote: 74, startBeat: 14, durationBeats: 2, lyric: 'join.' },
      ],
    },
    {
      id: 'ballad-backing-choir',
      name: 'Backing Chor (Aahs)',
      instrument: 'choir_alto',
      clef: 'treble',
      choralRole: 'Chor-Sphäre (Ooh/Aah)',
      volume: 0.85,
      isMuted: false,
      isSolo: false,
      notes: [
        { id: 'b-c1', pitch: 'D4', midiNote: 62, startBeat: 8, durationBeats: 4, lyric: 'Ooh' },
        { id: 'b-c2', pitch: 'G4', midiNote: 67, startBeat: 12, durationBeats: 4, lyric: 'Aah' },
      ],
    },
    {
      id: 'ballad-guitar',
      name: 'Akustikgitarre',
      instrument: 'guitar',
      clef: 'treble',
      volume: 0.8,
      isMuted: false,
      isSolo: false,
      notes: [
        { id: 'b-g1', pitch: 'G3', midiNote: 55, startBeat: 0, durationBeats: 0.5 },
        { id: 'b-g2', pitch: 'B3', midiNote: 59, startBeat: 0.5, durationBeats: 0.5 },
        { id: 'b-g3', pitch: 'D4', midiNote: 62, startBeat: 1, durationBeats: 0.5 },
        { id: 'b-g4', pitch: 'G4', midiNote: 67, startBeat: 1.5, durationBeats: 0.5 },
        { id: 'b-g5', pitch: 'E3', midiNote: 52, startBeat: 4, durationBeats: 0.5 },
        { id: 'b-g6', pitch: 'G3', midiNote: 55, startBeat: 4.5, durationBeats: 0.5 },
        { id: 'b-g7', pitch: 'B3', midiNote: 59, startBeat: 5, durationBeats: 0.5 },
        { id: 'b-g8', pitch: 'E4', midiNote: 64, startBeat: 5.5, durationBeats: 0.5 },
        { id: 'b-g9', pitch: 'C3', midiNote: 48, startBeat: 8, durationBeats: 0.5 },
        { id: 'b-g10', pitch: 'E3', midiNote: 52, startBeat: 8.5, durationBeats: 0.5 },
        { id: 'b-g11', pitch: 'G3', midiNote: 55, startBeat: 9, durationBeats: 0.5 },
        { id: 'b-g12', pitch: 'C4', midiNote: 60, startBeat: 9.5, durationBeats: 0.5 },
        { id: 'b-g13', pitch: 'D3', midiNote: 50, startBeat: 12, durationBeats: 0.5 },
        { id: 'b-g14', pitch: 'F#3', midiNote: 54, startBeat: 12.5, durationBeats: 0.5 },
        { id: 'b-g15', pitch: 'A3', midiNote: 57, startBeat: 13, durationBeats: 0.5 },
        { id: 'b-g16', pitch: 'D4', midiNote: 62, startBeat: 13.5, durationBeats: 0.5 },
      ],
    },
    {
      id: 'ballad-bass',
      name: 'Akustischer Bass',
      instrument: 'bass',
      clef: 'bass',
      volume: 0.85,
      isMuted: false,
      isSolo: false,
      notes: [
        { id: 'b-bs1', pitch: 'G2', midiNote: 43, startBeat: 0, durationBeats: 4 },
        { id: 'b-bs2', pitch: 'E2', midiNote: 40, startBeat: 4, durationBeats: 4 },
        { id: 'b-bs3', pitch: 'C2', midiNote: 36, startBeat: 8, durationBeats: 4 },
        { id: 'b-bs4', pitch: 'D2', midiNote: 38, startBeat: 12, durationBeats: 4 },
      ],
    },
  ],
};

export const ALL_PRESETS: Record<string, { label: string; description: string; data: ScoreData }> = {
  beethoven: {
    label: 'Ode an die Freude (SATB Chor & Klavier)',
    description: 'Klassischer 4-stimmiger Chorsatz mit deutschem Text & Klavierbegleitung',
    data: PRESET_ODE_AN_DIE_FREUDE,
  },
  mond: {
    label: 'Der Mond ist aufgegangen (3-stimmig & Streicher)',
    description: 'Traditioneller Choral mit feiner Terzenharmonisierung',
    data: PRESET_DER_MOND,
  },
  ballad: {
    label: 'Acoustic Ballad (Vocal, Backing-Chor & Gitarre)',
    description: 'Moderne Song-Partitur mit Solo-Gesang, Gitarren-Arpeggio und Chor',
    data: PRESET_ACOUSTIC_BALLAD,
  },
};
